//*****************************************************************************
//*****************************************************************************
//  FILENAME: LED_FIX.h
//   Version: 2.00, Updated on 2015/3/4 at 22:26:37                                          
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: LED_FIX User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef LED_FIX_INCLUDE
#define LED_FIX_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  LED_FIX_Stop
#pragma fastcall16  LED_FIX_Start
#pragma fastcall16  LED_FIX_On
#pragma fastcall16  LED_FIX_Off
#pragma fastcall16  LED_FIX_Switch
#pragma fastcall16  LED_FIX_Invert
#pragma fastcall16  LED_FIX_GetState


//-------------------------------------------------
// Constants for LED_FIX API's.
//-------------------------------------------------
//
#define  LED_FIX_ON   1
#define  LED_FIX_OFF  0

//-------------------------------------------------
// Prototypes of the LED_FIX API.
//-------------------------------------------------
extern void  LED_FIX_Start(void);                                     
extern void  LED_FIX_Stop(void);                                      
extern void  LED_FIX_On(void);                                      
extern void  LED_FIX_Off(void);                                      
extern void  LED_FIX_Switch(BYTE bSwitch);
extern void  LED_FIX_Invert(void);                                         
extern BYTE  LED_FIX_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
