/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
#include <m8c.h>
// TX address and mask defines
#pragma	ioport	TX_Data_ADDR:	0x0
BYTE			TX_Data_ADDR;
#pragma	ioport	TX_DriveMode_0_ADDR:	0x100
BYTE			TX_DriveMode_0_ADDR;
#pragma	ioport	TX_DriveMode_1_ADDR:	0x101
BYTE			TX_DriveMode_1_ADDR;
#pragma	ioport	TX_DriveMode_2_ADDR:	0x3
BYTE			TX_DriveMode_2_ADDR;
#pragma	ioport	TX_GlobalSelect_ADDR:	0x2
BYTE			TX_GlobalSelect_ADDR;
#pragma	ioport	TX_IntCtrl_0_ADDR:	0x102
BYTE			TX_IntCtrl_0_ADDR;
#pragma	ioport	TX_IntCtrl_1_ADDR:	0x103
BYTE			TX_IntCtrl_1_ADDR;
#pragma	ioport	TX_IntEn_ADDR:	0x1
BYTE			TX_IntEn_ADDR;
#define TX_MASK 0x4
// TX Shadow defines
//   TX_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define TX_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// LED_FIXPin address and mask defines
#pragma	ioport	LED_FIXPin_Data_ADDR:	0x0
BYTE			LED_FIXPin_Data_ADDR;
#pragma	ioport	LED_FIXPin_DriveMode_0_ADDR:	0x100
BYTE			LED_FIXPin_DriveMode_0_ADDR;
#pragma	ioport	LED_FIXPin_DriveMode_1_ADDR:	0x101
BYTE			LED_FIXPin_DriveMode_1_ADDR;
#pragma	ioport	LED_FIXPin_DriveMode_2_ADDR:	0x3
BYTE			LED_FIXPin_DriveMode_2_ADDR;
#pragma	ioport	LED_FIXPin_GlobalSelect_ADDR:	0x2
BYTE			LED_FIXPin_GlobalSelect_ADDR;
#pragma	ioport	LED_FIXPin_IntCtrl_0_ADDR:	0x102
BYTE			LED_FIXPin_IntCtrl_0_ADDR;
#pragma	ioport	LED_FIXPin_IntCtrl_1_ADDR:	0x103
BYTE			LED_FIXPin_IntCtrl_1_ADDR;
#pragma	ioport	LED_FIXPin_IntEn_ADDR:	0x1
BYTE			LED_FIXPin_IntEn_ADDR;
#define LED_FIXPin_MASK 0x8
// LED_FIXPin Shadow defines
//   LED_FIXPin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LED_FIXPin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// RX1 address and mask defines
#pragma	ioport	RX1_Data_ADDR:	0x0
BYTE			RX1_Data_ADDR;
#pragma	ioport	RX1_DriveMode_0_ADDR:	0x100
BYTE			RX1_DriveMode_0_ADDR;
#pragma	ioport	RX1_DriveMode_1_ADDR:	0x101
BYTE			RX1_DriveMode_1_ADDR;
#pragma	ioport	RX1_DriveMode_2_ADDR:	0x3
BYTE			RX1_DriveMode_2_ADDR;
#pragma	ioport	RX1_GlobalSelect_ADDR:	0x2
BYTE			RX1_GlobalSelect_ADDR;
#pragma	ioport	RX1_IntCtrl_0_ADDR:	0x102
BYTE			RX1_IntCtrl_0_ADDR;
#pragma	ioport	RX1_IntCtrl_1_ADDR:	0x103
BYTE			RX1_IntCtrl_1_ADDR;
#pragma	ioport	RX1_IntEn_ADDR:	0x1
BYTE			RX1_IntEn_ADDR;
#define RX1_MASK 0x10
// RX1 Shadow defines
//   RX1_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define RX1_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// RX2 address and mask defines
#pragma	ioport	RX2_Data_ADDR:	0x0
BYTE			RX2_Data_ADDR;
#pragma	ioport	RX2_DriveMode_0_ADDR:	0x100
BYTE			RX2_DriveMode_0_ADDR;
#pragma	ioport	RX2_DriveMode_1_ADDR:	0x101
BYTE			RX2_DriveMode_1_ADDR;
#pragma	ioport	RX2_DriveMode_2_ADDR:	0x3
BYTE			RX2_DriveMode_2_ADDR;
#pragma	ioport	RX2_GlobalSelect_ADDR:	0x2
BYTE			RX2_GlobalSelect_ADDR;
#pragma	ioport	RX2_IntCtrl_0_ADDR:	0x102
BYTE			RX2_IntCtrl_0_ADDR;
#pragma	ioport	RX2_IntCtrl_1_ADDR:	0x103
BYTE			RX2_IntCtrl_1_ADDR;
#pragma	ioport	RX2_IntEn_ADDR:	0x1
BYTE			RX2_IntEn_ADDR;
#define RX2_MASK 0x20
// RX2 Shadow defines
//   RX2_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define RX2_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
